Remove get_password_hash, unused
mitogen-hq/mitogen pull request #1146
Opened 2024-10-07 17:04 UTC by stefanor

spwd is removed in Python 3.13. But fortunately, this function itself is never used.

Part of: #1073

2024-10-07 17:09 UTC, moreati commented
refs 1073

2024-10-07 19:24 UTC, moreati commented
Notes
- `spwd.getspnam(name)` requires root (or *mumble* POSIX capability). It reads `/etc/shadow`. There's no interaction with any stdio or a tty
- `getpass.getpass(prompt='Password: ', stream=None)` requires no additional privilege. It writes to `stream` if supplied, or the controlling terminal if available, or stderr otherwise. It reads from `stream` if provided (I think), or the controlling tty, or stdin (with a warning).

2024-10-08 09:57 UTC, moreati commented
> This is just example code that is never called by anything.

Doubly so, get_password() (prev. `get_password_hash()`) isn't even called within its own example script.

2024-10-08 10:09 UTC, moreati requested changes
I think I prefer deleting the entire function; on the basis the function is unused and this file advertises itself as just the basics. Do you have a preference, or know of a reason to keep it?

2024-10-08 20:20 UTC, stefanor commented
Let's delete it. I was assuming it was there as a demonstrative example.

2024-10-08 22:25 UTC, moreati approved these changes

2024-10-09 09:40 UTC, merged